# reinit 函数逐行解析

In [8]:
import numpy as np
from scipy import ndimage

# 测试参数
nelx, nely = 6, 4

def reinit_detailed(struc):
    """
    根据给定的结构重置化水平集函数.

    该函数通过添加 void 单元的边界来扩展输入结构，计算到最近的 solid 和 void 单元
    的欧几里得距离，并计算水平集函数，该函数在 solid phase 内为正，在 void phase 中为负

    Parameters:
    - struc ( ndarray - (nely, nelx) ): 表示结构的 solid(1) 和 void(0) 单元

    Returns:
    - lsf ( ndarray - (nely+2, nelx+2) ): 表示重置化后的水平集函数
    """

    strucFull = np.zeros((nely + 2, nelx + 2))
    strucFull[1:-1, 1:-1] = struc
    print("strucFull:", strucFull.shape, "\n", strucFull)

    # Compute the distance to the nearest void (0-valued) cells.
    dist_to_0 = ndimage.distance_transform_edt(strucFull)
    print("dist_to_0:", dist_to_0.shape, "\n", dist_to_0)

    # Compute the distance to the nearest solid (1-valued) cells.
    dist_to_1 = ndimage.distance_transform_edt(1 - strucFull)
    print("dist_to_1:", dist_to_1.shape, "\n", dist_to_1.round(2))

    # Offset the distances by 0.5 to center the level set function on the boundaries.
    element_length = nelx / (2*nelx)
    temp_0 = dist_to_0 - element_length
    print("temp0:", temp_0.shape, "\n", temp_0)
    temp_1 = dist_to_1 - element_length
    print("temp1:", temp_1.shape, "\n", temp_1.round(2))

    # Calculate the level set function, ensuring the correct sign inside and outside the structure.
    lsf = -(1 - strucFull) * temp_1 + strucFull * temp_0
    print("lsf", lsf.shape, "\n", lsf.round(2))

    return lsf

# 创建一个测试用的结构数组（含有一个孔洞）
struc = np.ones((nely, nelx))
struc[8:12, 13:19] = 0
strucFull = np.zeros((nely + 2, nelx + 2))
strucFull[1:-1, 1:-1] = struc
print("strucFull:", strucFull.shape, "\n", strucFull)

# 调用 reinit 函数
lsf = reinit_detailed(struc)
print("lsf:", lsf.shape, "\n", lsf.round(3))

strucFull: (6, 8) 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
strucFull: (6, 8) 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
dist_to_0: (6, 8) 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
dist_to_1: (6, 8) 
 [[1.41 1.   1.   1.   1.   1.   1.   1.41]
 [1.   0.   0.   0.   0.   0.   0.   1.  ]
 [1.   0.   0.   0.   0.   0.   0.   1.  ]
 [1.   0.   0.   0.   0.   0.   0.   1.  ]
 [1.   0.   0.   0.   0.   0.   0.   1.  ]
 [1.41 1.   1.   1.   1.   1.   1.   1.41]]
temp0: (6, 8) 
 [[-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5  0.5  0.5  0.5  0.5  0.5 -0.5]
 [-0.5  0.5  1.5  1.5  1.5  1.5  0.5 -0.5]
 [-0.5  0.5  1.5  1.5  1.5 

# reinit 函数示例

In [4]:
from scipy import ndimage
import numpy as np

def reinit(nelx, nely, struc):

    strucFull = np.zeros((nely + 2, nelx + 2))
    strucFull[1:-1, 1:-1] = struc

    dist_to_0 = ndimage.distance_transform_edt(strucFull)
    dist_to_1 = ndimage.distance_transform_edt(strucFull - 1)

    element_length = nelx / (2*nelx)
    temp_0 = dist_to_0 - element_length
    temp_1 = dist_to_1 - element_length

    lsf = -(1 - strucFull) * temp_1 + strucFull * temp_0

    return lsf

import os
visualization_dir = 'visualization/'
os.makedirs(visualization_dir, exist_ok=True)

# 测试参数
nelx, nely = 32, 20
domain = [0, 32, 0, 20]

# 创建一个测试用的结构数组（含有一个孔洞）
struc = np.ones((nely, nelx))
struc[8:12, 13:19] = 0
strucFull = np.zeros((nely + 2, nelx + 2))
strucFull[1:-1, 1:-1] = struc
print("strucFull:", strucFull.shape, "\n", strucFull)

# 调用 reinit 函数
lsf = reinit(nelx, nely, struc)
print("lsf:", lsf.shape, "\n", lsf.round(3))

# 可视化
from fealpy.mesh import UniformMesh2d
hx = (domain[1] - domain[0]) / nelx
hy = (domain[3] - domain[2]) / nely
mesh = UniformMesh2d(extent=(0, nelx+2, 0, nely+2), 
                    h=(hx, hy), origin=(domain[0], domain[2]))

fname = os.path.join(visualization_dir, 'chaills_hole.vts')
mesh.to_vtk(filename=fname, 
                celldata={'strucFull': strucFull.flatten('F'),
                          'lsf': lsf.flatten('F')})

strucFull: (22, 34) 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1

'visualization/chaills_hole.vts'

# reinit 函数检验

In [6]:
import numpy as np
import os
from fealpy.decorator import cartesian
from fealpy.mesh import UniformMesh2d

# 非符号距离函数的水平集函数
@cartesian
def phi_nsd(p):
    x = p[..., 0]
    y = p[..., 1]
    val = (x - 0.5)**2 + (y - 0.75)**2 - 0.0115

    return val

# 符号距离函数的水平集函数
@cartesian
def phi_sd(p):
    x = p[..., 0]
    y = p[..., 1]
    val = np.sqrt((x - 0.5)**2 + (y - 0.75)**2) - 0.15

    return val

nelx, nely = 30, 20
domain = [0, 1, 0, 1]
hx = (domain[1] - domain[0]) / nelx
hy = (domain[3] - domain[2]) / nely
mesh = UniformMesh2d(extent=(0, nelx+2, 0, nely+2), 
                    h=(hx, hy), origin=(domain[0], domain[2]))

bc = mesh.entity_barycenter('cell')
phi_nsd_interpolate = phi_nsd(bc)
print("phi_nsd_interpolate:", phi_nsd_interpolate.shape, "\n", phi_nsd_interpolate.round(3))

phi_sd_interpolate = phi_sd(bc)
#print("phi_sd_interpolate:", phi_sd_interpolate.shape, "\n", phi_sd_interpolate.round(3))

# 非符号距离函数对应的单元密度
strucFull_nsd = (phi_nsd_interpolate >= 0).astype(int).reshape(nelx+2, nely+2).T
strucFull_nsd[0, :] = 0
strucFull_nsd[-1, :] = 0
strucFull_nsd[:, 0] = 0
strucFull_nsd[:, -1] = 0
#print("strucFull_nsd:", strucFull_nsd.shape, "\n", strucFull_nsd)
struc_nsd = strucFull_nsd[1:-1, 1:-1]
#print("struc_nsd:", struc_nsd.shape, "\n", struc_nsd)

# 符号距离函数对应的单元密度
strucFull_sd = (phi_sd_interpolate >= 0).astype(int).reshape(nelx+2, nely+2).T
strucFull_sd[0, :] = 0
strucFull_sd[-1, :] = 0
strucFull_sd[:, 0] = 0
strucFull_sd[:, -1] = 0
#print("strucFull_sd:", strucFull_sd.shape, "\n", strucFull_sd)
struc_sd = strucFull_sd[1:-1, 1:-1]
#print("struc_sd:", struc_sd.shape, "\n", struc_sd)

error_sd_nsd = np.sum(np.abs(struc_nsd - struc_sd))
#print("error_sd_nsd:", error_sd_nsd)

lsf = reinit(nelx=nelx, nely=nely, struc=struc_nsd)
print("lsf:", lsf.shape, "\n", lsf.round(3))

strucFull_lsf = (lsf.flatten('F') >= 0).astype(int).reshape(nelx+2, nely+2).T
strucFull_lsf[0, :] = 0
strucFull_lsf[-1, :] = 0
strucFull_lsf[:, 0] = 0
strucFull_lsf[:, -1] = 0
print("strucFull_lsf:", strucFull_lsf.shape, "\n", strucFull_lsf)
struc_lsf = strucFull_lsf[1:-1, 1:-1]
print("struc_lsf:", struc_lsf.shape, "\n", struc_lsf)

error_sd_lsf = np.sum(np.abs(struc_sd - struc_lsf))
print("error_sd_lsf:", error_sd_lsf)

error_nsd_lsf = np.sum(np.abs(struc_nsd - struc_lsf))
print("error_nsd_lsf:", error_nsd_lsf)

visualization_dir = 'visualization/'
os.makedirs(visualization_dir, exist_ok=True)

fname = os.path.join(visualization_dir, 'test_chaills_reinit.vts')
mesh.to_vtk(filename=fname, 
                celldata={'strucFull_nsd': strucFull_nsd.flatten('F'),
                          'strucFull_sd': strucFull_sd.flatten('F'),
                          'phi_nsd': phi_nsd_interpolate,
                          'phi_sd': phi_sd_interpolate,
                          'strucFull_lsf': strucFull_lsf.flatten('F'),
                          'lsf': lsf.flatten('F')})

phi_nsd_interpolate: (704,) 
 [ 0.748  0.678  0.613  0.553  0.498  0.448  0.403  0.363  0.328  0.298
  0.273  0.253  0.238  0.228  0.223  0.223  0.228  0.238  0.253  0.273
  0.298  0.328  0.717  0.647  0.582  0.522  0.467  0.417  0.372  0.332
  0.297  0.267  0.242  0.222  0.207  0.197  0.192  0.192  0.197  0.207
  0.222  0.242  0.267  0.297  0.688  0.618  0.553  0.493  0.438  0.388
  0.343  0.303  0.268  0.238  0.213  0.193  0.178  0.168  0.163  0.163
  0.168  0.178  0.193  0.213  0.238  0.268  0.661  0.591  0.526  0.466
  0.411  0.361  0.316  0.276  0.241  0.211  0.186  0.166  0.151  0.141
  0.136  0.136  0.141  0.151  0.166  0.186  0.211  0.241  0.637  0.567
  0.502  0.442  0.387  0.337  0.292  0.252  0.217  0.187  0.162  0.142
  0.127  0.117  0.112  0.112  0.117  0.127  0.142  0.162  0.187  0.217
  0.614  0.544  0.479  0.419  0.364  0.314  0.269  0.229  0.194  0.164
  0.139  0.119  0.104  0.094  0.089  0.089  0.094  0.104  0.119  0.139
  0.164  0.194  0.594  0.524  0.459  0.399  0.3

'visualization/test_chaills_reinit.vts'

In [2]:
import numpy as np
np.sqrt(0.0225)

0.15